import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav";
import AuthProvider from "./(components)/AuthProvider";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Footer from "./(components)/Footer";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import { User } from "./(models)/User";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Better Bytes",
	description: "Generated by Mike Fyke",
};

const getUsers = async () => {
	try {
		const res = await fetch("http://localhost:3000/api/Users", {
			cache: "no-store",
		});
		return res.json();
	} catch (error) {
		console.log("Failed to get users : ", error);
	}
};

const RootLayout = async ({
	children,
}: Readonly<{ children: React.ReactNode }>) => {
	const { users } = await getUsers();
	const session = await getServerSession(options);
	const selectedUser = users.filter((user: User) => {
		return user.email === session.user.email;
	});
	const userId = selectedUser[0]._id;

	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex flex-col h-screen max-h-screen">
					<Nav session={session} userId={userId} />
					<AuthProvider>
						<div className="flex-grow overflow-y-auto bg-page text-default-text">
							{children}
						</div>
					</AuthProvider>
					{session ? <Footer /> : null}
				</div>
			</body>
		</html>
	);
};

export default RootLayout;
