import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav";
import AuthProvider from "./(components)/AuthProvider";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Footer from "./(components)/Footer";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Better Bytes",
	description: "Generated by Mike Fyke",
};

const RootLayout = async ({
	children,
}: Readonly<{ children: React.ReactNode }>) => {
	const session = await getServerSession(options);

	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex flex-col h-screen max-h-screen">
					<Nav session={session} />
					<AuthProvider>
						<div className="flex-grow overflow-y-auto bg-page text-default-text">
							{children}
						</div>
					</AuthProvider>
					{session ? <Footer /> : null}
				</div>
			</body>
		</html>
	);
};

export default RootLayout;
